---
title: "Salary Data Content Analysis"
output: html_document
date: "2024-02-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r}
salary_data <- read.csv("Salary_Data.csv")
job_count <- salary_data %>% count(Job.Title)
words = c()
word_count = c()
i <- 1
job_words <- strsplit(job_count$Job.Title, split=" ")
job_words <- as.vector(job_words[2:length(job_words)])
for(word_group in job_words) {
  for(word in word_group){
    if(!(word %in% words)){
      words[i] <- word
      i <- i + 1
    }
  }
  
}
```


```{r}
BUSINESS <- c(" Account ", " Business ", " Product ", " Capital ", " UX ", " Advertising ", " Quality ", " Development ", " Marketing ", " Finance ", " Sales ", " Financial ", " Associate ", " Social ", " Intelligence ", " Copywriter ", " Advisor ", " Media ", " Public ")

# OTHER <- c(" Assistant ", " Creative ", " Clerk ", " Event ", " Front ", " Desk ", " Junior ", " Consultant ", " Writer ", " Back ", " Analyst ", " Chief ", " Content ", " Representative ", " Producer ", " End ", " Graphic ", " Generalist ", " end ", " Assurance ", " M ", " Chain ", " Driver ", " of ", " and ", " Juniour ", " Senior ", " Man ")

SERVICE <- c(" Customer ", " Success ", " Delivery ", " Service ", " Help ", " Support ")
```